"""Argument parser for the OMS typed runtime core."""
from __future__ import annotations
import argparse
from . import CORE_VERSION
from .context import DEFAULT_CONTEXT_BYTES
from .profiles import PROFILE_DEFS

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog='oms runtime', description='Typed semantic core over the existing hardened OMS execution plane.')
    parser.add_argument('--repo', default='.', help='project repository or directory')
    parser.add_argument('--pretty', action='store_true', help='pretty-print JSON')
    parser.add_argument('--version', action='version', version=CORE_VERSION)
    commands = parser.add_subparsers(dest='command', required=True)
    envelope = commands.add_parser('envelope', help='project the effective TaskEnvelope')
    envelope.add_argument('action', choices=('show', 'write'), nargs='?', default='show')
    envelope.add_argument('--output', default='.oms/runtime/effective-contract.json')
    evidence = commands.add_parser('evidence', help='criterion-level evidence coverage')
    evidence_sub = evidence.add_subparsers(dest='evidence_action', required=True)
    evidence_sub.add_parser('show')
    evidence_sub.add_parser('unbound')
    binding = evidence_sub.add_parser('bind')
    binding.add_argument('--criterion', required=True)
    binding.add_argument('--ref', required=True)
    binding.add_argument('--status', required=True, choices=('verified', 'failed', 'inconclusive', 'skipped_with_reason', 'stale'))
    binding.add_argument('--type', default='explicit-binding')
    binding.add_argument('--note', default='')
    binding.add_argument('--depends', action='append', default=[])
    revocation = evidence_sub.add_parser('revoke')
    revocation.add_argument('--binding', required=True)
    revocation.add_argument('--reason', default='')
    commands.add_parser('next', help='return the smallest currently valid internal actions')
    failure = commands.add_parser('failure', help='classify failures and inspect recovery metadata')
    failure_sub = failure.add_subparsers(dest='failure_action', required=True)
    classify = failure_sub.add_parser('classify')
    classify.add_argument('text')
    classify.add_argument('--exit', type=int, default=None)
    classify.add_argument('--code', default='')
    failure_sub.add_parser('catalog')
    context = commands.add_parser('context', help='compile a bounded context manifest and bundle')
    context.add_argument('--target', default='')
    context.add_argument('--file', action='append', default=[], help='PATH[:reason]')
    context.add_argument('--require', action='append', default=[])
    context.add_argument('--max-bytes', type=int, default=DEFAULT_CONTEXT_BYTES)
    context.add_argument('--bundle', default='')
    context.add_argument('--manifest', default='')
    context.add_argument('--allow-external', action='store_true')
    context.add_argument('--phase', default='implementation', choices=('orientation', 'implementation', 'verification', 'review', 'research'))
    profile = commands.add_parser('profile', help='optional capability contracts')
    profile_sub = profile.add_subparsers(dest='profile_action', required=True)
    profile_sub.add_parser('list')
    profile_sub.add_parser('current')
    show_profile = profile_sub.add_parser('show')
    show_profile.add_argument('name', choices=sorted(PROFILE_DEFS))
    check_profile = profile_sub.add_parser('check')
    check_profile.add_argument('profiles', nargs='+', choices=sorted(PROFILE_DEFS))
    apply_profile = profile_sub.add_parser('apply')
    apply_profile.add_argument('profiles', nargs='+', choices=sorted(PROFILE_DEFS))
    apply_profile.add_argument('--allow-missing', action='store_true')
    install_profile = profile_sub.add_parser('install-plan')
    install_profile.add_argument('profiles', nargs='+', choices=sorted(PROFILE_DEFS))
    install_profile.add_argument('--primary-provider', default='codex', choices=('codex', 'claude', 'agy'))
    install_apply = profile_sub.add_parser('install')
    install_apply.add_argument('profiles', nargs='+', choices=sorted(PROFILE_DEFS))
    install_apply.add_argument('--primary-provider', default='codex', choices=('codex', 'claude', 'agy'))
    install_apply.add_argument('--upgrade', action='store_true')
    install_apply.add_argument('--allow-missing', action='store_true')
    install_apply.add_argument('--receipt', default='')
    install_apply.add_argument('--dry-run', action='store_true')
    release = commands.add_parser('release', help='stable/edge update channel handling')
    release_sub = release.add_subparsers(dest='release_action', required=True)
    release_sub.add_parser('status')
    resolve = release_sub.add_parser('resolve')
    resolve.add_argument('channel', choices=('stable', 'edge'))
    resolve.add_argument('--fetch', action='store_true')
    apply_channel = release_sub.add_parser('apply')
    apply_channel.add_argument('channel', choices=('stable', 'edge'))
    apply_channel.add_argument('--no-fetch', action='store_true')
    apply_channel.add_argument('--tools', action='store_true')
    promote = release_sub.add_parser('promote')
    promote.add_argument('--commit', required=True)
    promote.add_argument('--version', required=True)
    promote.add_argument('--expected-manifest-digest', required=True)
    capsule = commands.add_parser('capsule', help='sanitized cross-machine continuity state')
    capsule_sub = capsule.add_subparsers(dest='capsule_action', required=True)
    export = capsule_sub.add_parser('export')
    export.add_argument('--output', default='')
    verify = capsule_sub.add_parser('verify')
    verify.add_argument('path')
    import_cmd = capsule_sub.add_parser('import')
    import_cmd.add_argument('path')
    diff = capsule_sub.add_parser('diff')
    diff.add_argument('left')
    diff.add_argument('right')
    backend = commands.add_parser('backend', help='trusted-local, isolated, or remote execution')
    backend_sub = backend.add_subparsers(dest='backend_action', required=True)
    for action in ('describe', 'check'):
        item = backend_sub.add_parser(action)
        item.add_argument('profile', choices=('trusted-local', 'isolated', 'remote'))
        item.add_argument('--image', default='')
        item.add_argument('--adapter', default='')
    run = backend_sub.add_parser('run')
    run.add_argument('profile', choices=('trusted-local', 'isolated', 'remote'))
    run.add_argument('--worktree', default='')
    run.add_argument('--image', default='')
    run.add_argument('--adapter', default='')
    run.add_argument('--allow-network', action='store_true')
    run.add_argument('--inherit-env', action='append', default=[])
    run.add_argument('--timeout-seconds', type=int, default=1200)
    run.add_argument('--log', default='')
    run.add_argument('--receipt', default='')
    run.add_argument('--log-limit', type=int, default=4 * 1024 * 1024)
    run.add_argument('--memory-mb', type=int, default=4096)
    run.add_argument('--cpus', type=float, default=2.0)
    run.add_argument('--pids-limit', type=int, default=512)
    run.add_argument('--tmpfs-mb', type=int, default=1024)
    run.add_argument('remainder', nargs='+')
    experiment = commands.add_parser('experiment', help='ExperimentContract v2 and invariant packs')
    experiment_sub = experiment.add_subparsers(dest='experiment_action', required=True)
    template_cmd = experiment_sub.add_parser('template')
    template_cmd.add_argument('--output', default='')
    validate_cmd = experiment_sub.add_parser('validate')
    validate_cmd.add_argument('contract')
    compare_cmd = experiment_sub.add_parser('compare')
    compare_cmd.add_argument('left')
    compare_cmd.add_argument('right')
    register_cmd = experiment_sub.add_parser('register')
    register_cmd.add_argument('contract')
    register_cmd.add_argument('--id', default='')
    show_cmd = experiment_sub.add_parser('show')
    show_cmd.add_argument('id')
    run_cmd = experiment_sub.add_parser('run')
    run_cmd.add_argument('--id', required=True)
    run_cmd.add_argument('--arm', required=True, choices=('baseline', 'treatment'))
    run_cmd.add_argument('--seed', required=True, type=int)
    run_cmd.add_argument('--metrics', required=True)
    run_cmd.add_argument('--profile', default='trusted-local', choices=('trusted-local', 'isolated', 'remote'))
    run_cmd.add_argument('--image', default='')
    run_cmd.add_argument('--adapter', default='')
    run_cmd.add_argument('--worktree', default='')
    run_cmd.add_argument('--timeout-seconds', type=int, default=86400)
    run_cmd.add_argument('--allow-existing-metrics', action='store_true')
    run_cmd.add_argument('remainder', nargs='+')
    summarize_cmd = experiment_sub.add_parser('summarize')
    summarize_cmd.add_argument('--id', required=True)
    evaluate_cmd = experiment_sub.add_parser('evaluate')
    evaluate_cmd.add_argument('contract')
    evaluate_cmd.add_argument('results')
    invariant_cmd = experiment_sub.add_parser('invariants')
    invariant_cmd.add_argument('contract')
    invariant_cmd.add_argument('--profile', default='trusted-local', choices=('trusted-local', 'isolated', 'remote'))
    invariant_cmd.add_argument('--image', default='')
    invariant_cmd.add_argument('--adapter', default='')
    invariant_cmd.add_argument('--timeout-seconds', type=int, default=1200)
    benchmark = commands.add_parser('benchmark', help='harness effectiveness telemetry')
    benchmark_sub = benchmark.add_subparsers(dest='benchmark_action', required=True)
    benchmark_sub.add_parser('show')
    benchmark_sub.add_parser('snapshot')
    benchmark_record = benchmark_sub.add_parser('record')
    benchmark_record.add_argument('--task-id', required=True)
    benchmark_record.add_argument('--status', required=True, choices=('verified', 'failed', 'partial', 'blocked'))
    benchmark_record.add_argument('--human-corrections', type=int, default=0)
    benchmark_record.add_argument('--escaped-defects', type=int, default=0)
    benchmark_record.add_argument('--reverted-lines', type=int, default=0)
    benchmark_record.add_argument('--false-refusals', type=int, default=0)
    benchmark_record.add_argument('--duplicate-work', type=int, default=0)
    benchmark_record.add_argument('--note', default='')
    benchmark_compare = benchmark_sub.add_parser('compare')
    benchmark_compare.add_argument('left')
    benchmark_compare.add_argument('right')
    doctor = commands.add_parser('doctor', help='validate the runtime projection without replacing OMS doctor')
    doctor.add_argument('--strict', action='store_true')
    return parser
